### 추가 전처리 코드

- Input: gm게산 코드를 통해 생성된 csv file (gm_data 폴더에 존재)
- Precess: 아웃라이어 발견, Stationary하게 데이터 수정 등의 추가 전처리 진행하는 코드
- Output: 시각화에 사용할 csv file

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("../gm_data/SK_gm_df.csv")

In [3]:
df

,Date,영업이익(원),금융손익(비영업)(원),관계기업투자등관련손익(비영업)(원),종가(원),수정주가(원),PBR,us_10_treasury,Quarter,equity,...,kospi_수익률_1주후,kospi_수익률_2주후,kospi_수익률_1달후,kospi_수익률_3달후,kospi_수익률_6달후,상대수익률_1주후,상대수익률_2주후,상대수익률_1달후,상대수익률_3달후,상대수익률_6달후
0,2022-07-01,1357569000000,-191014000000,-75909000000,52800,52800,0.99,2.889,2022Q3,10515800000000,...,1.960172,1.108694,6.336376,-5.904776,0.358721,0.312556,0.217063,-4.821225,3.063867,-7.555690
1,2022-07-04,1357569000000,-191014000000,-75909000000,53600,53600,1.01,2.889,2022Q3,10515800000000,...,1.735827,3.256471,6.603802,-5.625697,0.730318,0.876113,-1.204232,-6.603802,-1.090721,-8.845990
2,2022-07-05,1357569000000,-191014000000,-75909000000,54200,54200,1.02,2.809,2022Q3,10515800000000,...,-1.025716,1.246485,4.178022,-7.955061,-0.383896,2.501731,-1.615489,-6.761048,1.681999,-8.656695
3,2022-07-06,1357569000000,-191014000000,-75909000000,53800,53800,1.01,2.913,2022Q3,10515800000000,...,1.596856,4.137857,7.392635,-3.605138,-0.504363,2.120616,-5.067225,-8.693751,-1.785196,-9.904559
4,2022-07-07,1357569000000,-191014000000,-75909000000,53800,53800,1.01,3.008,2022Q3,10515800000000,...,-0.511935,3.208279,5.947902,-5.100098,-4.192751,2.556545,-6.368130,-7.063143,-0.290237,-7.703160
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
242,2023-06-23,958187000000,-97545000000,9672000000,47400,47400,0.91,3.739,2023Q2,10685400000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
243,2023-06-26,958187000000,-97545000000,9672000000,47350,47350,0.91,3.719,2023Q2,10685400000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
244,2023-06-27,958187000000,-97545000000,9672000000,47600,47600,0.92,3.768,2023Q2,10685400000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
245,2023-06-28,958187000000,-97545000000,9672000000,47650,47650,0.92,3.710,2023Q2,10685400000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
246,2023-06-29,958187000000,-97545000000,9672000000,46250,46250,0.89,3.854,2023Q2,10685400000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN